### ISSUE TITLE
用例期望 作为 步骤 的子主题录入

### ISSUE THREAD

**Issue by honeyhaha** [pengchenglin/freemind2testlink#1]
非常感谢这个共享，对于我们公司目前用例转换导入工作，带来了很大的便益，提高工作效率，棒棒哒，点赞……
但是否可以将 用例期望 作为步骤 的子主题 来转换吗？ 这个更便于我们目前已编写用例的转换工作。
![1212](https://user-images.githubusercontent.com/37134895/40714780-27086ad2-6436-11e8-8045-d70bb100f058.png)

**Comment by pengchenglin** [comment]
这样改动起来比较麻烦 ，其实我们现在步骤都不写的  直接标题写清楚 就一股脑都导进去了  
写太细了 测起来麻烦  也不利于测试人员的探索性测试能力的提升吧
